/**
 * Template-based AGENTS.md generation — no API key required.
 *
 * When ANTHROPIC_API_KEY is not set, agents-sync falls back to stack-specific
 * templates populated with data from the scanner corpus.  The output is a
 * complete AGENTS.md that gives AI tools useful project context immediately.
 *
 * Supported stacks: typescript/node, python, go, rust, java, generic.
 */

import type { RawCorpus } from "../scanner/index.js";
import { metadataFromCorpus } from "../extractor/extractor.js";
import type { ProjectMetadata } from "../extractor/schema.js";

export type TemplateName = "typescript-node" | "python" | "go" | "rust" | "java" | "generic";

export interface TemplateResult {
  agentsMd: string;
  metadata: ProjectMetadata;
  templateUsed: TemplateName;
}

// ---------------------------------------------------------------------------
// Stack detection
// ---------------------------------------------------------------------------

export function detectStack(corpus: RawCorpus): TemplateName {
  const lang = corpus.manifest.language.toLowerCase();
  if (lang === "typescript" || lang === "javascript") return "typescript-node";
  if (lang === "python") return "python";
  if (lang === "go") return "go";
  if (lang === "rust") return "rust";
  if (lang === "java" || lang === "kotlin") return "java";
  return "generic";
}

// ---------------------------------------------------------------------------
// Template entry point
// ---------------------------------------------------------------------------

export function generateFromTemplate(corpus: RawCorpus, projectPath: string): TemplateResult {
  const template = detectStack(corpus);
  const metadata = metadataFromCorpus(corpus, projectPath);
  const agentsMd = renderTemplate(template, corpus, metadata, projectPath);
  return { agentsMd, metadata, templateUsed: template };
}

// ---------------------------------------------------------------------------
// Shared rendering helpers
// ---------------------------------------------------------------------------

function bullets(items: string[]): string {
  return items.map((i) => `- ${i}`).join("\n");
}

function renderHeader(name: string): string {
  return `# AGENTS.md

<!-- Generated by agents-sync (template mode) on ${new Date().toISOString().slice(0, 10)} -->
<!-- No ANTHROPIC_API_KEY was set — this file was generated from a template.  -->
<!-- Run \`agents-sync init .\` with an API key for AI-powered output.        -->
<!-- Edit this file, then run \`agents-sync sync\` to propagate changes.     -->

## Project

${name}`;
}

function renderBoundaries(meta: ProjectMetadata): string {
  const alwaysDo = meta.boundaries.alwaysDo.length
    ? bullets(meta.boundaries.alwaysDo)
    : "- Run the test suite before marking work as done\n- Follow the naming conventions above\n- Keep changes focused — one logical change per commit";

  const askFirst =
    "- Adding or removing dependencies\n- Changing the database schema\n- Modifying CI/CD configuration\n- Introducing a new architectural pattern";

  const neverDo =
    "- Commit secrets, API keys, or credentials to the repository\n- Modify files in auto-generated directories without understanding the generator";

  return `## Boundaries

### Always
${alwaysDo}

### Ask First
${askFirst}

### Never
${neverDo}`;
}

// ---------------------------------------------------------------------------
// TypeScript / Node.js template
// ---------------------------------------------------------------------------

function renderTypeScriptNode(corpus: RawCorpus, meta: ProjectMetadata, _projectPath: string): string {
  const { manifest, structure } = corpus;
  const name = meta.project.name;
  const fw = meta.project.framework ? ` / ${meta.project.framework}` : "";
  const testCmd = manifest.scripts?.test ?? "npm test";
  const buildCmd = manifest.scripts?.build ?? "npm run build";
  const dirs = structure.topLevelDirs.slice(0, 8);
  const hasSrc = dirs.includes("src");
  const testDirs = structure.testDirs.length ? structure.testDirs.join(", ") : (hasSrc ? "src/**/*.test.ts" : "tests/");
  const entryPoints = structure.entryPoints.length ? structure.entryPoints.slice(0, 3).join(", ") : "src/index.ts";

  const stackLines = [
    `- **Language**: TypeScript${manifest.projectVersion ? ` (project v${manifest.projectVersion})` : ""}`,
    manifest.runtime ? `- **Runtime**: ${manifest.runtime}` : "- **Runtime**: Node.js",
    meta.project.framework ? `- **Framework**: ${meta.project.framework}` : "",
    meta.stack.database ? `- **Database**: ${meta.stack.database}` : "",
    meta.stack.auth ? `- **Auth**: ${meta.stack.auth}` : "",
    meta.stack.testing ? `- **Testing**: ${meta.stack.testing}` : "- **Testing**: check package.json",
    meta.stack.deploy ? `- **Deploy**: ${meta.stack.deploy}` : "",
    meta.stack.other.length ? `- **Other**: ${meta.stack.other.join(", ")}` : "",
  ].filter(Boolean).join("\n");

  const archLines = dirs.length
    ? dirs.map((d) => `- \`${d}/\` — `).join("\n") + "\n\n> Fill in descriptions as you explore the project."
    : "- (run `agents-sync init .` with an API key to auto-detect directories)";

  return `${renderHeader(`${name} — TypeScript${fw} project.`)}

## Stack

${stackLines}

## Architecture

Entry points: \`${entryPoints}\`

${archLines}

## Conventions

- TypeScript strict mode — avoid \`any\`, use \`unknown\` and type guards
- Named exports; default exports only where the framework requires them
- File names: ${structure.namingConvention === "camelCase" ? "camelCase" : "kebab-case"} (e.g. \`user-service.ts\`)
- Import order: node built-ins → npm packages → local files
- Prefer \`async/await\` over raw Promises; always handle rejections

## Testing

- **Run all tests**: \`${testCmd}\`
${manifest.scripts?.build ? `- **Build**: \`${buildCmd}\`` : ""}
- **Test location**: \`${testDirs}\`
- Write a test for every new exported function

## Gotchas

- (Add project-specific gotchas here as you discover them)
- Run \`agents-sync init .\` with an API key to auto-detect gotchas from TODO/FIXME comments

${renderBoundaries(meta)}
`;
}

// ---------------------------------------------------------------------------
// Python template
// ---------------------------------------------------------------------------

function renderPython(corpus: RawCorpus, meta: ProjectMetadata, _projectPath: string): string {
  const { manifest, structure } = corpus;
  const name = meta.project.name;
  const fw = meta.project.framework ? ` / ${meta.project.framework}` : "";
  const testCmd = manifest.scripts?.test ?? "pytest";
  const deps = manifest.dependencies.slice(0, 12);

  const stackLines = [
    `- **Language**: Python`,
    meta.project.framework ? `- **Framework**: ${meta.project.framework}` : "",
    meta.stack.database ? `- **Database**: ${meta.stack.database}` : "",
    meta.stack.testing ? `- **Testing**: ${meta.stack.testing}` : "- **Testing**: pytest",
    meta.stack.deploy ? `- **Deploy**: ${meta.stack.deploy}` : "",
    deps.length ? `- **Key dependencies**: ${deps.join(", ")}` : "",
  ].filter(Boolean).join("\n");

  const dirs = structure.topLevelDirs.slice(0, 8);

  return `${renderHeader(`${name} — Python${fw} project.`)}

## Stack

${stackLines}

## Architecture

${dirs.length ? dirs.map((d) => `- \`${d}/\` — `).join("\n") : "- (run `agents-sync init .` with an API key to auto-detect directories)"}

## Conventions

- Follow PEP 8; use type hints everywhere
- Use \`pathlib.Path\` over \`os.path\`
- Prefer \`dataclasses\` or Pydantic models over raw dicts
- Tests in \`tests/\` directory, prefixed \`test_\`

## Testing

- **Run all tests**: \`${testCmd}\`
- **Coverage**: \`pytest --cov\`

## Gotchas

- (Add project-specific gotchas here as you discover them)

${renderBoundaries(meta)}
`;
}

// ---------------------------------------------------------------------------
// Go template
// ---------------------------------------------------------------------------

function renderGo(corpus: RawCorpus, meta: ProjectMetadata, _projectPath: string): string {
  const { structure } = corpus;
  const name = meta.project.name;
  const fw = meta.project.framework ? ` / ${meta.project.framework}` : "";
  const dirs = structure.topLevelDirs.slice(0, 8);

  return `${renderHeader(`${name} — Go${fw} project.`)}

## Stack

- **Language**: Go
${meta.project.framework ? `- **Framework**: ${meta.project.framework}` : ""}
${meta.stack.database ? `- **Database**: ${meta.stack.database}` : ""}
- **Testing**: \`go test ./...\`

## Architecture

${dirs.length ? dirs.map((d) => `- \`${d}/\` — `).join("\n") : "- (run `agents-sync init .` with an API key to auto-detect directories)"}

## Conventions

- Error values are returned, not panicked — always handle \`err != nil\`
- Package names are single, lowercase words
- Interfaces are defined where they are used, not where they are implemented
- File names: snake_case

## Testing

- **Run all tests**: \`go test ./...\`
- **With coverage**: \`go test -cover ./...\`
- **Race detector**: \`go test -race ./...\`

## Gotchas

- (Add project-specific gotchas here as you discover them)

${renderBoundaries(meta)}
`;
}

// ---------------------------------------------------------------------------
// Rust template
// ---------------------------------------------------------------------------

function renderRust(corpus: RawCorpus, meta: ProjectMetadata, _projectPath: string): string {
  const { structure } = corpus;
  const name = meta.project.name;
  const dirs = structure.topLevelDirs.slice(0, 8);

  return `${renderHeader(`${name} — Rust project.`)}

## Stack

- **Language**: Rust
${meta.project.framework ? `- **Framework**: ${meta.project.framework}` : ""}
${meta.stack.database ? `- **Database**: ${meta.stack.database}` : ""}
- **Testing**: \`cargo test\`

## Architecture

${dirs.length ? dirs.map((d) => `- \`${d}/\` — `).join("\n") : "- (run `agents-sync init .` with an API key to auto-detect directories)"}

## Conventions

- Use \`clippy\` — no warnings allowed: \`cargo clippy -- -D warnings\`
- Prefer owned types over references in public APIs unless performance requires otherwise
- \`unwrap()\` only in tests; propagate errors with \`?\` in production code
- File names: snake_case

## Testing

- **Run all tests**: \`cargo test\`
- **Doc tests**: included in \`cargo test\`
- Unit tests go in the same file as the code under \`#[cfg(test)]\`

## Gotchas

- (Add project-specific gotchas here as you discover them)

${renderBoundaries(meta)}
`;
}

// ---------------------------------------------------------------------------
// Java template
// ---------------------------------------------------------------------------

function renderJava(corpus: RawCorpus, meta: ProjectMetadata, _projectPath: string): string {
  const { manifest, structure } = corpus;
  const name = meta.project.name;
  const fw = meta.project.framework ? ` / ${meta.project.framework}` : "";
  const testCmd = manifest.scripts?.test ?? "mvn test";
  const dirs = structure.topLevelDirs.slice(0, 8);

  return `${renderHeader(`${name} — Java${fw} project.`)}

## Stack

- **Language**: Java${meta.project.framework ? ` / ${meta.project.framework}` : ""}
${meta.stack.database ? `- **Database**: ${meta.stack.database}` : ""}
${meta.stack.testing ? `- **Testing**: ${meta.stack.testing}` : "- **Testing**: JUnit"}
${meta.stack.deploy ? `- **Deploy**: ${meta.stack.deploy}` : ""}

## Architecture

${dirs.length ? dirs.map((d) => `- \`${d}/\` — `).join("\n") : "- (run `agents-sync init .` with an API key to auto-detect directories)"}

## Conventions

- Package names: lowercase, reverse domain (e.g. \`com.example.service\`)
- Class names: PascalCase
- One public class per file; file name matches class name
- Use constructor injection for dependencies (not field injection)

## Testing

- **Run all tests**: \`${testCmd}\`
- Tests in \`src/test/java/\`; class names end in \`Test\`

## Gotchas

- (Add project-specific gotchas here as you discover them)

${renderBoundaries(meta)}
`;
}

// ---------------------------------------------------------------------------
// Generic template (fallback)
// ---------------------------------------------------------------------------

function renderGeneric(corpus: RawCorpus, meta: ProjectMetadata, _projectPath: string): string {
  const { manifest, structure } = corpus;
  const name = meta.project.name;
  const lang = manifest.language;
  const testCmd = manifest.scripts?.test;
  const dirs = structure.topLevelDirs.slice(0, 8);

  return `${renderHeader(`${name} — ${lang} project.`)}

## Stack

- **Language**: ${lang}
${meta.project.framework ? `- **Framework**: ${meta.project.framework}` : ""}
${meta.stack.database ? `- **Database**: ${meta.stack.database}` : ""}
${meta.stack.testing ? `- **Testing**: ${meta.stack.testing}` : ""}

## Architecture

${dirs.length ? dirs.map((d) => `- \`${d}/\` — `).join("\n") : "- (describe key directories here)"}

## Conventions

- (Add project conventions here — be specific, not generic)
- Run \`agents-sync init .\` with an API key to auto-detect conventions

## Testing

${testCmd ? `- **Run all tests**: \`${testCmd}\`` : "- (add the test command here)"}

## Gotchas

- (Add project-specific gotchas here as you discover them)

${renderBoundaries(meta)}
`;
}

// ---------------------------------------------------------------------------
// Dispatch
// ---------------------------------------------------------------------------

function renderTemplate(
  template: TemplateName,
  corpus: RawCorpus,
  meta: ProjectMetadata,
  projectPath: string,
): string {
  switch (template) {
    case "typescript-node": return renderTypeScriptNode(corpus, meta, projectPath);
    case "python": return renderPython(corpus, meta, projectPath);
    case "go": return renderGo(corpus, meta, projectPath);
    case "rust": return renderRust(corpus, meta, projectPath);
    case "java": return renderJava(corpus, meta, projectPath);
    default: return renderGeneric(corpus, meta, projectPath);
  }
}
