import { describe, it, expect, vi, beforeEach } from "vitest";
import { generateAgentsMd } from "../../../src/generator/agents-md.js";
import type { ProjectMetadata } from "../../../src/extractor/schema.js";

vi.mock("../../../src/lib/claude-client.js", () => ({
  callClaude: vi.fn(),
}));

import { callClaude } from "../../../src/lib/claude-client.js";
const mockCallClaude = vi.mocked(callClaude);

const SAMPLE_METADATA: ProjectMetadata = {
  project: {
    name: "acme-dashboard",
    description: "Internal analytics tool for the sales team",
    language: "typescript",
    framework: "nextjs",
  },
  stack: {
    testing: "vitest",
    deploy: "vercel",
    other: [],
  },
  architecture: {
    keyDirs: {
      "src/app": "Next.js pages and layouts",
      "src/lib": "shared utilities",
      "src/features": "feature modules",
    },
    entryPoints: ["src/index.ts"],
  },
  conventions: [
    "kebab-case filenames throughout",
    "Named exports only — no default exports except page/layout components",
    "Validate all external input with Zod",
  ],
  gotchas: [
    "Never import PrismaClient directly — use lib/db.ts singleton. Direct imports cause connection pool exhaustion in Vercel serverless.",
  ],
  boundaries: {
    alwaysDo: ["Run tests before committing"],
    askFirst: ["Database schema changes"],
    never: ["Commit .env or .env.local", "Use `any` type"],
  },
  testing: {
    framework: "vitest",
    command: "npm test",
    location: "tests/",
  },
  deployment: {
    target: "vercel",
    notes: [],
  },
};

const GOOD_AGENTS_MD = `# AGENTS.md

<!-- Generated by agents-sync v1.0.0 on 2026-05-20 -->

## Project Overview
Acme Dashboard is an internal analytics tool for the sales team, built with Next.js 14 App Router.

## Tech Stack
- TypeScript / Next.js 14
- Testing: Vitest
- Deploy: Vercel

## Architecture
- \`src/app/\` — Next.js pages and layouts
- \`src/lib/\` — shared utilities
- \`src/features/\` — feature modules

## Conventions
1. kebab-case filenames throughout
2. Named exports only — no default exports except page/layout components
3. Validate all external input with Zod

## Gotchas
1. Never import PrismaClient directly — use lib/db.ts singleton. Direct imports cause connection pool exhaustion in Vercel serverless.

## Testing
Run: npm test

## Boundaries

### Always
- Run tests before committing

### Ask First
- Database schema changes

### Never
- Commit .env or .env.local
- Use \`any\` type`;

describe("generateAgentsMd", () => {
  beforeEach(() => {
    mockCallClaude.mockReset();
  });

  it("returns Claude output with corrected header when correct", async () => {
    mockCallClaude.mockResolvedValueOnce({
      content: GOOD_AGENTS_MD,
      inputTokens: 500,
      outputTokens: 200,
    });

    const result = await generateAgentsMd(SAMPLE_METADATA);

    expect(result).toContain("# AGENTS.md");
    expect(result.trim().startsWith("# AGENTS.md")).toBe(true);
  });

  it("injects timestamp comment when response lacks it", async () => {
    const responseWithoutComment = "# AGENTS.md\n\n## Project Overview\nSome project.\n\n## Conventions\n1. Use kebab-case filenames\n2. Named exports only\n\n## Boundaries\n### Never\n- Commit secrets";
    mockCallClaude.mockResolvedValueOnce({
      content: responseWithoutComment,
      inputTokens: 200,
      outputTokens: 100,
    });

    const result = await generateAgentsMd(SAMPLE_METADATA);

    expect(result).toContain("agents-sync");
    expect(result).toContain("# AGENTS.md");
  });

  it("throws GENERATION_FAILED when response does not start with # AGENTS.md", async () => {
    mockCallClaude.mockResolvedValueOnce({
      content: "Here is your AGENTS.md file:\n\nSome content without the header",
      inputTokens: 100,
      outputTokens: 50,
    });

    await expect(generateAgentsMd(SAMPLE_METADATA)).rejects.toMatchObject({
      code: "GENERATION_FAILED",
    });
  });

  it("passes project metadata into the prompt", async () => {
    mockCallClaude.mockResolvedValueOnce({
      content: GOOD_AGENTS_MD,
      inputTokens: 500,
      outputTokens: 200,
    });

    await generateAgentsMd(SAMPLE_METADATA);

    const [, userPrompt] = mockCallClaude.mock.calls[0];
    expect(userPrompt).toContain("acme-dashboard");
    expect(userPrompt).toContain("nextjs");
    expect(userPrompt).toContain("kebab-case");
  });
});
