import { describe, it, expect } from "vitest";
import { deriveClineRules } from "../../../src/derivers/cline.js";
import type { ProjectMetadata } from "../../../src/extractor/schema.js";

const METADATA: ProjectMetadata = {
  project: { name: "my-app", description: "A test app", language: "typescript", framework: "next.js" },
  stack: { other: [] },
  architecture: { keyDirs: {}, entryPoints: [] },
  conventions: ["Use named exports", "Prefer const"],
  gotchas: ["DB connection is singleton"],
  boundaries: { alwaysDo: ["Run tests before commit"], askFirst: [], never: ["Commit .env files"] },
  testing: { command: "npm test" },
  deployment: { notes: [] },
};

const AGENTS_MD = `# AGENTS.md
<!-- Generated by agents-sync -->

## Conventions
- Use named exports
- Prefer const

## Gotchas
- DB connection is singleton

### Never
- Commit .env files

### Always do
- Run tests before commit
`;

describe("deriveClineRules", () => {
  it("output starts with .clinerules header", async () => {
    const result = await deriveClineRules({
      projectPath: "/nonexistent",
      agentsMdContent: AGENTS_MD,
      metadata: METADATA,
      preserveCustom: false,
    });
    expect(result).toMatch(/^# \.clinerules/);
  });

  it("output is under 400 words", async () => {
    const result = await deriveClineRules({
      projectPath: "/nonexistent",
      agentsMdContent: AGENTS_MD,
      metadata: METADATA,
      preserveCustom: false,
    });
    const wordCount = result.split(/\s+/).filter(Boolean).length;
    expect(wordCount).toBeLessThan(400);
  });

  it("includes conventions section", async () => {
    const result = await deriveClineRules({
      projectPath: "/nonexistent",
      agentsMdContent: AGENTS_MD,
      metadata: METADATA,
      preserveCustom: false,
    });
    expect(result).toContain("## Conventions");
    expect(result).toContain("Use named exports");
  });

  it("includes Never section from boundaries", async () => {
    const result = await deriveClineRules({
      projectPath: "/nonexistent",
      agentsMdContent: AGENTS_MD,
      metadata: METADATA,
      preserveCustom: false,
    });
    expect(result).toContain("## Never");
    expect(result).toContain("Commit .env files");
  });

  it("includes Always section from boundaries", async () => {
    const result = await deriveClineRules({
      projectPath: "/nonexistent",
      agentsMdContent: AGENTS_MD,
      metadata: METADATA,
      preserveCustom: false,
    });
    expect(result).toContain("## Always");
    expect(result).toContain("Run tests before commit");
  });

  it("includes test command", async () => {
    const result = await deriveClineRules({
      projectPath: "/nonexistent",
      agentsMdContent: AGENTS_MD,
      metadata: METADATA,
      preserveCustom: false,
    });
    expect(result).toContain("npm test");
  });

  it("includes language/framework in header", async () => {
    const result = await deriveClineRules({
      projectPath: "/nonexistent",
      agentsMdContent: AGENTS_MD,
      metadata: METADATA,
      preserveCustom: false,
    });
    expect(result).toContain("typescript");
    expect(result).toContain("next.js");
  });
});
