import { describe, it, expect } from "vitest";
import { deriveGeminiMd } from "../../../src/derivers/gemini.js";
import type { ProjectMetadata } from "../../../src/extractor/schema.js";

const METADATA: ProjectMetadata = {
  project: { name: "my-app", description: "A test app", language: "typescript", framework: "next.js" },
  stack: { other: [] },
  architecture: { keyDirs: {}, entryPoints: [] },
  conventions: ["Use named exports"],
  gotchas: ["DB is singleton"],
  boundaries: { alwaysDo: ["Run tests before commit"], askFirst: [], never: ["Commit secrets"] },
  testing: { command: "npm test" },
  deployment: { notes: [] },
};

const AGENTS_MD = `# AGENTS.md
<!-- Generated by agents-sync -->

Project overview paragraph.

## Conventions
- Use named exports

## Gotchas
- DB is singleton

### Never
- Commit secrets

### Always do
- Run tests before commit
`;

describe("deriveGeminiMd", () => {
  it("output includes full AGENTS.md content", async () => {
    const result = await deriveGeminiMd({
      projectPath: "/nonexistent",
      agentsMdContent: AGENTS_MD,
      metadata: METADATA,
      preserveCustom: false,
    });
    expect(result).toContain("# AGENTS.md");
    expect(result).toContain("Project overview paragraph.");
    expect(result).toContain("## Conventions");
  });

  it("output includes Gemini CLI section", async () => {
    const result = await deriveGeminiMd({
      projectPath: "/nonexistent",
      agentsMdContent: AGENTS_MD,
      metadata: METADATA,
      preserveCustom: false,
    });
    expect(result).toContain("## Gemini CLI Notes");
    expect(result).toContain("agents-sync");
  });

  it("does not include custom blocks when preserveCustom is false", async () => {
    const result = await deriveGeminiMd({
      projectPath: "/nonexistent",
      agentsMdContent: AGENTS_MD,
      metadata: METADATA,
      preserveCustom: false,
    });
    expect(result).not.toContain("AGENTS-SYNC:CUSTOM");
  });
});
