import { describe, it, expect } from "vitest";
import { deriveWindsurfRules } from "../../../src/derivers/windsurf.js";
import type { ProjectMetadata } from "../../../src/extractor/schema.js";

const METADATA: ProjectMetadata = {
  project: { name: "my-app", description: "A test app", language: "typescript", framework: "next.js" },
  stack: { other: [] },
  architecture: { keyDirs: {}, entryPoints: [] },
  conventions: ["Use named exports", "Prefer const"],
  gotchas: ["DB connection is singleton"],
  boundaries: { alwaysDo: ["Run tests before commit"], askFirst: [], never: ["Commit .env files"] },
  testing: { command: "npm test" },
  deployment: { notes: [] },
};

const AGENTS_MD = `# AGENTS.md
<!-- Generated by agents-sync -->

## Conventions
- Use named exports
- Prefer const

## Gotchas
- DB connection is singleton

### Never
- Commit .env files

### Always do
- Run tests before commit
`;

describe("deriveWindsurfRules", () => {
  it("output starts with .windsurfrules header", async () => {
    const result = await deriveWindsurfRules({
      projectPath: "/nonexistent",
      agentsMdContent: AGENTS_MD,
      metadata: METADATA,
      preserveCustom: false,
    });
    expect(result).toMatch(/^# \.windsurfrules/);
  });

  it("output is under 400 words", async () => {
    const result = await deriveWindsurfRules({
      projectPath: "/nonexistent",
      agentsMdContent: AGENTS_MD,
      metadata: METADATA,
      preserveCustom: false,
    });
    const wordCount = result.split(/\s+/).filter(Boolean).length;
    expect(wordCount).toBeLessThan(400);
  });

  it("includes Always: directives from conventions", async () => {
    const result = await deriveWindsurfRules({
      projectPath: "/nonexistent",
      agentsMdContent: AGENTS_MD,
      metadata: METADATA,
      preserveCustom: false,
    });
    expect(result).toContain("Always: Use named exports");
  });

  it("includes Never: directives from gotchas", async () => {
    const result = await deriveWindsurfRules({
      projectPath: "/nonexistent",
      agentsMdContent: AGENTS_MD,
      metadata: METADATA,
      preserveCustom: false,
    });
    expect(result).toContain("Never: DB connection is singleton");
  });

  it("includes test command", async () => {
    const result = await deriveWindsurfRules({
      projectPath: "/nonexistent",
      agentsMdContent: AGENTS_MD,
      metadata: METADATA,
      preserveCustom: false,
    });
    expect(result).toContain("npm test");
  });

  it("includes language/framework header line", async () => {
    const result = await deriveWindsurfRules({
      projectPath: "/nonexistent",
      agentsMdContent: AGENTS_MD,
      metadata: METADATA,
      preserveCustom: false,
    });
    expect(result).toContain("typescript");
    expect(result).toContain("next.js");
  });
});
