import { callClaude } from "../lib/claude-client.js";
import { AgentsSyncError } from "../lib/errors.js";
import type { ProjectMetadata } from "../extractor/schema.js";
import type { McpScanResult } from "../scanner/mcp.js";
import { formatMcpSection } from "../scanner/mcp.js";

const SYSTEM_PROMPT = `You are writing an AGENTS.md file — the canonical AI context file for a software project.

This file will be read by AI coding assistants (Claude, Cursor, Copilot, Codex) to understand the project.
A session starting with ONLY this file must be able to:
1. Identify the correct directory for a new feature
2. Know the naming convention for new files
3. Know the exact test command to run
4. Avoid the project's top gotchas

Quality rules:
- Every convention must be SPECIFIC: "kebab-case filenames" not "follow conventions"
- Every gotcha must include CONSEQUENCE: "Do not import PrismaClient directly — causes pool exhaustion"
- Architecture section must name REAL directories (from the data provided)
- No section may be generic advice that applies to any project
- No empty sections — omit a section entirely if you have no real data for it
- Length: 400–900 words

Format the output as valid markdown starting with "# AGENTS.md".`;

const TEMPLATE = `# AGENTS.md

<!-- Generated by agents-sync v1.0.0 on {DATE} -->
<!-- Edit this file, then run /agents-sync sync to propagate changes to all tool files -->

## Project Overview
{OVERVIEW}

## Tech Stack
{STACK}

## Architecture
{ARCHITECTURE}

## Conventions
{CONVENTIONS}

## Gotchas
{GOTCHAS}

## Testing
{TESTING}

## Boundaries

### Always
{ALWAYS}

### Ask First
{ASK_FIRST}

### Never
{NEVER}`;

/** Appends an MCP Servers section to an already-generated AGENTS.md if servers were found. */
export function appendMcpSection(agentsMd: string, mcp: McpScanResult): string {
  if (!mcp.hasAny) return agentsMd;
  const section = formatMcpSection(mcp);
  return `${agentsMd.trimEnd()}\n\n${section}`;
}

export async function generateAgentsMd(metadata: ProjectMetadata): Promise<string> {
  const userPrompt = buildPrompt(metadata);
  const { content } = await callClaude(SYSTEM_PROMPT, userPrompt, 2048);

  // Ensure it starts with the header
  if (!content.trim().startsWith("# AGENTS.md") && !content.trim().startsWith("# agents-sync")) {
    throw new AgentsSyncError(
      "GENERATION_FAILED",
      "Generated output did not produce a valid AGENTS.md header.",
      "Run with AGENTS_SYNC_DEBUG=1 to inspect output.",
    );
  }

  // Inject generated timestamp if Claude didn't include a comment
  const dated = content.includes("Generated by agents-sync")
    ? content
    : content.replace(
        "# AGENTS.md",
        `# AGENTS.md\n\n<!-- Generated by agents-sync v1.0.0 on ${new Date().toISOString().slice(0, 10)} -->\n<!-- Edit this file, then run /agents-sync sync to propagate changes to all tool files -->`,
      );

  return dated.trim();
}

function buildPrompt(m: ProjectMetadata): string {
  const lines: string[] = ["Here is the extracted project metadata. Generate the AGENTS.md:\n"];

  lines.push(`PROJECT: ${m.project.name} — ${m.project.description}`);
  lines.push(`Language: ${m.project.language}${m.project.framework ? `, Framework: ${m.project.framework}` : ""}${m.project.version ? `, v${m.project.version}` : ""}`);

  lines.push("\nSTACK:");
  if (m.stack.runtime) lines.push(`  Runtime: ${m.stack.runtime}`);
  if (m.stack.database) lines.push(`  Database: ${m.stack.database}`);
  if (m.stack.auth) lines.push(`  Auth: ${m.stack.auth}`);
  if (m.stack.testing) lines.push(`  Testing: ${m.stack.testing}`);
  if (m.stack.deploy) lines.push(`  Deploy: ${m.stack.deploy}`);
  if (m.stack.other.length > 0) lines.push(`  Other: ${m.stack.other.join(", ")}`);

  lines.push("\nARCHITECTURE:");
  if (m.architecture.style) lines.push(`  Style: ${m.architecture.style}`);
  lines.push(`  Entry points: ${m.architecture.entryPoints.join(", ") || "unknown"}`);
  for (const [dir, desc] of Object.entries(m.architecture.keyDirs)) {
    lines.push(`  ${dir}: ${desc}`);
  }

  if (m.conventions.length > 0) {
    lines.push("\nCONVENTIONS:");
    m.conventions.forEach((c, i) => lines.push(`  ${i + 1}. ${c}`));
  }

  if (m.gotchas.length > 0) {
    lines.push("\nGOTCHAS:");
    m.gotchas.forEach((g, i) => lines.push(`  ${i + 1}. ${g}`));
  }

  lines.push("\nBOUNDARIES:");
  if (m.boundaries.alwaysDo.length > 0) lines.push(`  Always: ${m.boundaries.alwaysDo.join("; ")}`);
  if (m.boundaries.askFirst.length > 0) lines.push(`  Ask first: ${m.boundaries.askFirst.join("; ")}`);
  if (m.boundaries.never.length > 0) lines.push(`  Never: ${m.boundaries.never.join("; ")}`);

  lines.push("\nTESTING:");
  if (m.testing.framework) lines.push(`  Framework: ${m.testing.framework}`);
  if (m.testing.command) lines.push(`  Command: ${m.testing.command}`);
  if (m.testing.location) lines.push(`  Location: ${m.testing.location}`);
  if (m.testing.coverageCommand) lines.push(`  Coverage: ${m.testing.coverageCommand}`);

  if (m.deployment.target || m.deployment.notes.length > 0) {
    lines.push("\nDEPLOYMENT:");
    if (m.deployment.target) lines.push(`  Target: ${m.deployment.target}`);
    if (m.deployment.command) lines.push(`  Command: ${m.deployment.command}`);
    m.deployment.notes.forEach((n) => lines.push(`  Note: ${n}`));
  }

  lines.push(`\nUse this template structure:\n${TEMPLATE.replace("{DATE}", new Date().toISOString().slice(0, 10))}`);
  lines.push("\nGenerate the complete AGENTS.md now:");

  return lines.join("\n");
}
