import { callClaude } from "../lib/claude-client.js";
import { AgentsSyncError } from "../lib/errors.js";
import type { ProjectMetadata } from "../extractor/schema.js";
import type { McpScanResult } from "../scanner/mcp.js";
import { formatMcpSection } from "../scanner/mcp.js";
import type { CodegraphSummary } from "../scanner/codegraph.js";
import { formatCodegraphContext } from "../scanner/codegraph.js";
import type { RawCorpus } from "../scanner/index.js";

const SYSTEM_PROMPT = `You are writing an AGENTS.md file — the canonical AI context file for a software project.

This file will be read by AI coding assistants (Claude, Cursor, Copilot, Codex) to understand the project.
A session starting with ONLY this file must be able to:
1. Identify the correct directory for a new feature
2. Know the naming convention for new files
3. Know the exact test command to run
4. Avoid the project's top gotchas

Quality rules:
- Every convention must be SPECIFIC: "kebab-case filenames" not "follow conventions"
- Every gotcha must include CONSEQUENCE: "Do not import PrismaClient directly — causes pool exhaustion"
- Architecture section must name REAL directories (from the data provided)
- No section may be generic advice that applies to any project
- No empty sections — omit a section entirely if you have no real data for it
- Length: 400–900 words

Format the output as valid markdown starting with "# AGENTS.md".`;

const TEMPLATE = `# AGENTS.md

<!-- Generated by agents-sync v1.0.0 on {DATE} -->
<!-- Edit this file, then run /agents-sync sync to propagate changes to all tool files -->

## Project Overview
{OVERVIEW}

## Tech Stack
{STACK}

## Architecture
{ARCHITECTURE}

## Conventions
{CONVENTIONS}

## Gotchas
{GOTCHAS}

## Testing
{TESTING}

## Boundaries

### Always
{ALWAYS}

### Ask First
{ASK_FIRST}

### Never
{NEVER}`;

/** Appends an MCP Servers section to an already-generated AGENTS.md if servers were found. */
export function appendMcpSection(agentsMd: string, mcp: McpScanResult): string {
  if (!mcp.hasAny) return agentsMd;
  const section = formatMcpSection(mcp);
  return `${agentsMd.trimEnd()}\n\n${section}`;
}

/** Appends a Code Graph section from .codegraph/ data if the index was found. */
export function appendCodegraphSection(agentsMd: string, codegraph: CodegraphSummary): string {
  if (!codegraph.available) return agentsMd;
  const section = formatCodegraphContext(codegraph);
  if (!section) return agentsMd;
  return `${agentsMd.trimEnd()}\n\n${section}`;
}

export async function generateAgentsMd(metadata: ProjectMetadata): Promise<string> {
  const userPrompt = buildPrompt(metadata);
  const { content } = await callClaude(SYSTEM_PROMPT, userPrompt, 2048);

  // Ensure it starts with the header
  if (!content.trim().startsWith("# AGENTS.md") && !content.trim().startsWith("# agents-sync")) {
    throw new AgentsSyncError(
      "GENERATION_FAILED",
      "Generated output did not produce a valid AGENTS.md header.",
      "Run with AGENTS_SYNC_DEBUG=1 to inspect output.",
    );
  }

  return injectTimestamp(content);
}

// ─── Single-call pipeline ────────────────────────────────────────────────────

const DIRECT_SYSTEM_PROMPT = `You are analyzing a software project and writing its AGENTS.md file in a single pass.

AGENTS.md is the canonical AI context file read by Claude Code, Cursor, GitHub Copilot, Gemini CLI, and other AI coding assistants.
A session that starts with ONLY this file must be able to:
1. Identify the correct directory for a new feature
2. Know the naming convention for new files
3. Know the exact test command to run
4. Avoid the project's most common gotchas

Your task:
- Extract concrete facts from the provided project data
- NEVER invent directories, frameworks, or conventions you cannot see in the data
- Write the complete AGENTS.md directly — no intermediate steps, no JSON
- Start your response with "# AGENTS.md"

Quality requirements:
- Every convention must be SPECIFIC: "kebab-case filenames" not "follow conventions"
- Every gotcha must include CONSEQUENCE: "Don't X — causes Y"
- Architecture section must name REAL directories from the provided data
- No section may contain generic advice that applies to any project
- Omit sections entirely if you have no real data for them
- Length: 400–900 words`;

/**
 * Generates AGENTS.md from raw corpus in a single Claude API call.
 * This replaces the two-call approach (extract → JSON → generate → AGENTS.md)
 * and is faster, cheaper, and produces better output since Claude has the full corpus context.
 */
export async function generateAgentsMdDirect(corpus: RawCorpus): Promise<string> {
  const userPrompt = buildCorpusPrompt(corpus) + `\n\nNow write the complete AGENTS.md directly:\n${TEMPLATE.replace("{DATE}", new Date().toISOString().slice(0, 10))}`;

  for (let attempt = 1; attempt <= 2; attempt++) {
    const { content } = await callClaude(DIRECT_SYSTEM_PROMPT, userPrompt, 4096);
    const trimmed = content.trim();

    if (trimmed.startsWith("# AGENTS.md") || trimmed.startsWith("# agents-sync")) {
      return injectTimestamp(trimmed);
    }

    if (attempt === 2) {
      throw new AgentsSyncError(
        "GENERATION_FAILED",
        "Generated output did not start with '# AGENTS.md' after 2 attempts.",
        "Run with AGENTS_SYNC_DEBUG=1 to inspect Claude's output.",
      );
    }

    // Retry with stronger instruction
    const retryPrompt = `${userPrompt}\n\nIMPORTANT: Your previous output did not start with "# AGENTS.md". Output ONLY the markdown file starting with exactly "# AGENTS.md" — no explanation, no preamble.`;
    const { content: retryContent } = await callClaude(DIRECT_SYSTEM_PROMPT, retryPrompt, 4096);
    const retryTrimmed = retryContent.trim();
    if (retryTrimmed.startsWith("# AGENTS.md") || retryTrimmed.startsWith("# agents-sync")) {
      return injectTimestamp(retryTrimmed);
    }
    throw new AgentsSyncError(
      "GENERATION_FAILED",
      "Generated output did not start with '# AGENTS.md' after 2 attempts.",
      "Run with AGENTS_SYNC_DEBUG=1 to inspect Claude's output.",
    );
  }

  throw new AgentsSyncError("GENERATION_FAILED", "Unexpected generation failure.");
}

function injectTimestamp(content: string): string {
  if (content.includes("Generated by agents-sync")) return content.trim();
  return content
    .replace(
      "# AGENTS.md",
      `# AGENTS.md\n\n<!-- Generated by agents-sync on ${new Date().toISOString().slice(0, 10)} -->\n<!-- Edit this file, then run /agents-sync sync to propagate changes to all tool files -->`,
    )
    .trim();
}

/** Build the corpus prompt shared by both the direct generator and the two-call extractor. */
export function buildCorpusPrompt(corpus: RawCorpus): string {
  const sections: string[] = [];

  sections.push("=== MANIFEST / DEPENDENCIES ===");
  sections.push(`Language: ${corpus.manifest.language}`);
  if (corpus.manifest.framework) sections.push(`Detected framework: ${corpus.manifest.framework}`);
  if (corpus.manifest.runtime) sections.push(`Runtime: ${corpus.manifest.runtime}`);
  if (corpus.manifest.projectName) sections.push(`Project name: ${corpus.manifest.projectName}`);
  sections.push(`Dependencies (${corpus.manifest.dependencies.length}): ${corpus.manifest.dependencies.slice(0, 25).join(", ")}`);
  if (corpus.manifest.devDependencies.length > 0) {
    sections.push(`Dev deps: ${corpus.manifest.devDependencies.slice(0, 15).join(", ")}`);
  }
  if (Object.keys(corpus.manifest.scripts).length > 0) {
    sections.push(`Scripts: ${JSON.stringify(corpus.manifest.scripts)}`);
  }

  sections.push("\n=== PROJECT STRUCTURE ===");
  sections.push(`Top-level dirs: ${corpus.structure.topLevelDirs.join(", ")}`);
  sections.push(`Entry points: ${corpus.structure.entryPoints.join(", ") || "none detected"}`);
  sections.push(`Test dirs: ${corpus.structure.testDirs.join(", ") || "none detected"}`);
  sections.push(`Naming convention: ${corpus.structure.namingConvention}`);
  sections.push(`Total files: ~${corpus.structure.totalFileCount}`);
  sections.push(`\nDirectory tree:\n${corpus.structure.tree}`);

  if (corpus.source.files.length > 0) {
    sections.push("\n=== SAMPLED SOURCE FILES ===");
    sections.push(`Import style: ${corpus.source.importStyle}`);
    if (corpus.source.detectedPatterns.length > 0) {
      sections.push(`Detected patterns: ${corpus.source.detectedPatterns.join(", ")}`);
    }
    for (const f of corpus.source.files.slice(0, 10)) {
      sections.push(`\n--- ${f.path} ---`);
      sections.push(f.content.slice(0, 800));
    }
  }

  if (corpus.docs.readme) {
    sections.push("\n=== README ===");
    sections.push(corpus.docs.readme.slice(0, 1500));
  }
  if (corpus.docs.contributing) {
    sections.push("\n=== CONTRIBUTING ===");
    sections.push(corpus.docs.contributing.slice(0, 800));
  }
  if (corpus.docs.existingAgentsMd) {
    sections.push("\n=== EXISTING AGENTS.MD (use as baseline, preserve custom sections) ===");
    sections.push(corpus.docs.existingAgentsMd);
  }
  if (corpus.docs.existingClaudeMd) {
    sections.push("\n=== EXISTING CLAUDE.MD (extract unique conventions) ===");
    sections.push(corpus.docs.existingClaudeMd.slice(0, 1000));
  }

  if (corpus.gotchas.length > 0) {
    sections.push("\n=== GOTCHAS FOUND IN SOURCE (TODO/FIXME/HACK comments) ===");
    for (const g of corpus.gotchas) {
      sections.push(`${g.type} in ${g.file}:${g.line} — ${g.comment}`);
    }
  }

  if (corpus.codegraph?.available) {
    const cgContext = formatCodegraphContext(corpus.codegraph);
    if (cgContext) {
      sections.push("\n=== CODE GRAPH (structural analysis) ===");
      sections.push(cgContext);
    }
  }

  return sections.join("\n");
}

// ─── Two-call pipeline (kept for backward compat / testing) ──────────────────

function buildPrompt(m: ProjectMetadata): string {
  const lines: string[] = ["Here is the extracted project metadata. Generate the AGENTS.md:\n"];

  lines.push(`PROJECT: ${m.project.name} — ${m.project.description}`);
  lines.push(`Language: ${m.project.language}${m.project.framework ? `, Framework: ${m.project.framework}` : ""}${m.project.version ? `, v${m.project.version}` : ""}`);

  lines.push("\nSTACK:");
  if (m.stack.runtime) lines.push(`  Runtime: ${m.stack.runtime}`);
  if (m.stack.database) lines.push(`  Database: ${m.stack.database}`);
  if (m.stack.auth) lines.push(`  Auth: ${m.stack.auth}`);
  if (m.stack.testing) lines.push(`  Testing: ${m.stack.testing}`);
  if (m.stack.deploy) lines.push(`  Deploy: ${m.stack.deploy}`);
  if (m.stack.other.length > 0) lines.push(`  Other: ${m.stack.other.join(", ")}`);

  lines.push("\nARCHITECTURE:");
  if (m.architecture.style) lines.push(`  Style: ${m.architecture.style}`);
  lines.push(`  Entry points: ${m.architecture.entryPoints.join(", ") || "unknown"}`);
  for (const [dir, desc] of Object.entries(m.architecture.keyDirs)) {
    lines.push(`  ${dir}: ${desc}`);
  }

  if (m.conventions.length > 0) {
    lines.push("\nCONVENTIONS:");
    m.conventions.forEach((c, i) => lines.push(`  ${i + 1}. ${c}`));
  }

  if (m.gotchas.length > 0) {
    lines.push("\nGOTCHAS:");
    m.gotchas.forEach((g, i) => lines.push(`  ${i + 1}. ${g}`));
  }

  lines.push("\nBOUNDARIES:");
  if (m.boundaries.alwaysDo.length > 0) lines.push(`  Always: ${m.boundaries.alwaysDo.join("; ")}`);
  if (m.boundaries.askFirst.length > 0) lines.push(`  Ask first: ${m.boundaries.askFirst.join("; ")}`);
  if (m.boundaries.never.length > 0) lines.push(`  Never: ${m.boundaries.never.join("; ")}`);

  lines.push("\nTESTING:");
  if (m.testing.framework) lines.push(`  Framework: ${m.testing.framework}`);
  if (m.testing.command) lines.push(`  Command: ${m.testing.command}`);
  if (m.testing.location) lines.push(`  Location: ${m.testing.location}`);
  if (m.testing.coverageCommand) lines.push(`  Coverage: ${m.testing.coverageCommand}`);

  if (m.deployment.target || m.deployment.notes.length > 0) {
    lines.push("\nDEPLOYMENT:");
    if (m.deployment.target) lines.push(`  Target: ${m.deployment.target}`);
    if (m.deployment.command) lines.push(`  Command: ${m.deployment.command}`);
    m.deployment.notes.forEach((n) => lines.push(`  Note: ${n}`));
  }

  lines.push(`\nUse this template structure:\n${TEMPLATE.replace("{DATE}", new Date().toISOString().slice(0, 10))}`);
  lines.push("\nGenerate the complete AGENTS.md now:");

  return lines.join("\n");
}
