import { describe, it, expect, beforeEach, afterEach } from "vitest";
import fs from "node:fs/promises";
import path from "node:path";
import os from "node:os";
import crypto from "node:crypto";
import { runValidate } from "../../src/tools/validate.js";
import { buildSnapshot, saveSnapshot } from "../../src/snapshot/writer.js";
import type { ManagedFile } from "../../src/snapshot/schema.js";

function sha256(s: string): string {
  return crypto.createHash("sha256").update(s).digest("hex");
}

async function makeProject(
  files: Record<string, string>,
  managedFiles?: ManagedFile[],
): Promise<string> {
  const dir = await fs.mkdtemp(path.join(os.tmpdir(), "agents-sync-validate-"));
  for (const [rel, content] of Object.entries(files)) {
    const abs = path.join(dir, rel);
    await fs.mkdir(path.dirname(abs), { recursive: true });
    await fs.writeFile(abs, content, "utf-8");
  }
  if (managedFiles) {
    const snapshot = buildSnapshot({
      projectPath: dir,
      manifestContent: "{}",
      structureHash: sha256("src"),
      filesManaged: managedFiles,
      language: "typescript",
      framework: null,
      topLevelDirs: ["src"],
      dependencyCount: 0,
      totalFiles: 1,
    });
    await saveSnapshot(snapshot);
  }
  return dir;
}

describe("runValidate", () => {
  let tmpDirs: string[] = [];

  afterEach(async () => {
    for (const d of tmpDirs) await fs.rm(d, { recursive: true, force: true });
    tmpDirs = [];
  });

  async function project(
    files: Record<string, string>,
    managed?: ManagedFile[],
  ): Promise<string> {
    const dir = await makeProject(files, managed);
    tmpDirs.push(dir);
    return dir;
  }

  it("reports all-in-sync when hashes match", async () => {
    const claudeContent = "# CLAUDE.md\nGenerated by agents-sync\n";
    const agentsMdContent = "# AGENTS.md\n";
    const dir = await project(
      { "AGENTS.md": agentsMdContent, "CLAUDE.md": claudeContent },
      [
        { tool: "agents-md", path: "", sha256: sha256(agentsMdContent) },
        { tool: "claude", path: "", sha256: sha256(claudeContent) },
      ],
    );
    // Fix paths to be absolute
    const snapshot = buildSnapshot({
      projectPath: dir,
      manifestContent: "{}",
      structureHash: sha256("src"),
      filesManaged: [
        { tool: "agents-md", path: path.join(dir, "AGENTS.md"), sha256: sha256(agentsMdContent) },
        { tool: "claude", path: path.join(dir, "CLAUDE.md"), sha256: sha256(claudeContent) },
      ],
      language: "typescript",
      framework: null,
      topLevelDirs: ["src"],
      dependencyCount: 0,
      totalFiles: 1,
    });
    const { saveSnapshot: save } = await import("../../src/snapshot/writer.js");
    await save(snapshot);

    const result = await runValidate({ projectPath: dir });
    expect(result.hasSnapshot).toBe(true);
    expect(result.allInSync).toBe(true);
    const claudeFile = result.toolFiles.find((f) => f.tool === "claude");
    expect(claudeFile?.status).toBe("in-sync");
  });

  it("reports drifted when file content has changed", async () => {
    const originalContent = "# CLAUDE.md\nOriginal\n";
    const newContent = "# CLAUDE.md\nModified by hand\n";
    const dir = await project({ "AGENTS.md": "# AGENTS.md\n", "CLAUDE.md": newContent }, []);
    const snapshot = buildSnapshot({
      projectPath: dir,
      manifestContent: "{}",
      structureHash: sha256("src"),
      filesManaged: [
        { tool: "agents-md", path: path.join(dir, "AGENTS.md"), sha256: sha256("# AGENTS.md\n") },
        { tool: "claude", path: path.join(dir, "CLAUDE.md"), sha256: sha256(originalContent) },
      ],
      language: "typescript",
      framework: null,
      topLevelDirs: ["src"],
      dependencyCount: 0,
      totalFiles: 1,
    });
    const { saveSnapshot: save } = await import("../../src/snapshot/writer.js");
    await save(snapshot);

    const result = await runValidate({ projectPath: dir });
    expect(result.allInSync).toBe(false);
    const claudeFile = result.toolFiles.find((f) => f.tool === "claude");
    expect(claudeFile?.status).toBe("drifted");
  });

  it("reports missing when a managed file does not exist on disk", async () => {
    const dir = await project({ "AGENTS.md": "# AGENTS.md\n" }, []);
    const snapshot = buildSnapshot({
      projectPath: dir,
      manifestContent: "{}",
      structureHash: sha256("src"),
      filesManaged: [
        { tool: "agents-md", path: path.join(dir, "AGENTS.md"), sha256: sha256("# AGENTS.md\n") },
        { tool: "cursor", path: path.join(dir, ".cursorrules"), sha256: sha256("rules") },
      ],
      language: "typescript",
      framework: null,
      topLevelDirs: ["src"],
      dependencyCount: 0,
      totalFiles: 1,
    });
    const { saveSnapshot: save } = await import("../../src/snapshot/writer.js");
    await save(snapshot);

    const result = await runValidate({ projectPath: dir });
    expect(result.allInSync).toBe(false);
    const cursorFile = result.toolFiles.find((f) => f.tool === "cursor");
    expect(cursorFile?.status).toBe("missing");
  });

  it("returns hasSnapshot=false when no snapshot exists", async () => {
    const dir = await project({ "AGENTS.md": "# AGENTS.md\n", "CLAUDE.md": "# CLAUDE" });
    const result = await runValidate({ projectPath: dir });
    expect(result.hasSnapshot).toBe(false);
    expect(result.allInSync).toBe(false);
  });

  it("no-snapshot: existing files reported as in-sync, not drifted (--strict should not fail)", async () => {
    // A freshly cloned repo with committed context files but no .agents-sync/ snapshot
    // should not fail --strict — there is no baseline to compare against.
    const dir = await project({ "AGENTS.md": "# AGENTS.md\n", "CLAUDE.md": "# CLAUDE.md\n" });
    const result = await runValidate({ projectPath: dir, strict: true });
    expect(result.hasSnapshot).toBe(false);
    const claudeFile = result.toolFiles.find((f) => f.tool === "claude");
    expect(claudeFile?.status).toBe("in-sync");
    // allInSync reflects whether all expected files exist — CLAUDE.md exists so it's true
    // (other tool files are missing and will lower allInSync, but the key assertion is
    // that existing files are NOT marked drifted)
    expect(claudeFile?.status).not.toBe("drifted");
  });

  it("no-snapshot: missing context files set allInSync=false so --strict can catch absent files", async () => {
    // If someone deleted .cursorrules and there is no snapshot, strict should still fail
    // because the file is simply absent (not "drifted without baseline").
    const dir = await project({ "AGENTS.md": "# AGENTS.md\n" }); // no CLAUDE.md etc.
    const result = await runValidate({ projectPath: dir });
    expect(result.hasSnapshot).toBe(false);
    expect(result.allInSync).toBe(false);
    const claudeFile = result.toolFiles.find((f) => f.tool === "claude");
    expect(claudeFile?.status).toBe("missing");
  });

  it("checks roo and aider files via snapshot", async () => {
    const rooContent = '{"customModes":[]}';
    const aiderContent = "# CONVENTIONS\n";
    const dir = await project(
      { "AGENTS.md": "# AGENTS.md\n", ".roomodes": rooContent, "CONVENTIONS.md": aiderContent },
      [],
    );
    const snapshot = buildSnapshot({
      projectPath: dir,
      manifestContent: "{}",
      structureHash: sha256("src"),
      filesManaged: [
        { tool: "agents-md", path: path.join(dir, "AGENTS.md"), sha256: sha256("# AGENTS.md\n") },
        { tool: "roo", path: path.join(dir, ".roomodes"), sha256: sha256(rooContent) },
        { tool: "aider", path: path.join(dir, "CONVENTIONS.md"), sha256: sha256(aiderContent) },
      ],
      language: "typescript",
      framework: null,
      topLevelDirs: ["src"],
      dependencyCount: 0,
      totalFiles: 1,
    });
    const { saveSnapshot: save } = await import("../../src/snapshot/writer.js");
    await save(snapshot);

    const result = await runValidate({ projectPath: dir });
    expect(result.toolFiles.find((f) => f.tool === "roo")?.status).toBe("in-sync");
    expect(result.toolFiles.find((f) => f.tool === "aider")?.status).toBe("in-sync");
  });

  it("detects drift in roo file when modified", async () => {
    const originalRoo = '{"customModes":[]}';
    const modifiedRoo = '{"customModes":[],"extra":true}';
    const dir = await project({ "AGENTS.md": "# AGENTS.md\n", ".roomodes": modifiedRoo }, []);
    const snapshot = buildSnapshot({
      projectPath: dir,
      manifestContent: "{}",
      structureHash: sha256("src"),
      filesManaged: [
        { tool: "agents-md", path: path.join(dir, "AGENTS.md"), sha256: sha256("# AGENTS.md\n") },
        { tool: "roo", path: path.join(dir, ".roomodes"), sha256: sha256(originalRoo) },
      ],
      language: "typescript",
      framework: null,
      topLevelDirs: ["src"],
      dependencyCount: 0,
      totalFiles: 1,
    });
    const { saveSnapshot: save } = await import("../../src/snapshot/writer.js");
    await save(snapshot);

    const result = await runValidate({ projectPath: dir });
    expect(result.toolFiles.find((f) => f.tool === "roo")?.status).toBe("drifted");
  });

  it("report contains canonical status and tool file lines", async () => {
    const dir = await project({ "AGENTS.md": "# AGENTS.md\n" });
    const result = await runValidate({ projectPath: dir });
    expect(result.report).toContain("AGENTS.md (canonical)");
  });
});
