/**
 * agents-sync load-context
 *
 * Installs only the Claude Code SessionStart hook — no scanner, no API call,
 * no AGENTS.md generation.  Works on any project that already has an AGENTS.md,
 * whether it was written by hand, generated by this tool, or synced from another
 * AI tool.
 *
 * This is the minimal entry point for the reading side of the agents-sync
 * pipeline.  For the full pipeline (generate + derive + drift detection) use
 * `init` instead.
 */
import path from "node:path";
import { fileExists } from "../lib/file-utils.js";
import {
  installSessionStartHook,
  removeSessionStartHook,
  installPreToolUseHook,
  removePreToolUseHook,
  installLazyHook,
  removeLazyHook,
  globalClaudeDir,
} from "./install-hook.js";

export interface LoadContextOptions {
  projectPath: string;
  dryRun?: boolean;
  /**
   * Also install a PreToolUse hook that re-injects AGENTS.md on every tool
   * call.  Protects against Claude Code dropping context after compaction.
   * Only needed if you are NOT using CLAUDE.md (which re-reads @AGENTS.md
   * automatically after compaction).
   * @default false
   */
  antiCompaction?: boolean;
  /**
   * Install a SessionStart instruction that tells Claude to check for AGENTS.md
   * in subdirectories it enters.  Useful in monorepos where each package has
   * its own AGENTS.md below the project root.
   * @default false
   */
  lazy?: boolean;
  /**
   * Install into ~/.claude/settings.json instead of <project>/.claude/settings.json.
   * Covers every Claude Code session on this machine — no per-project setup needed.
   * When true, projectPath is only used to check for AGENTS.md presence.
   * @default false
   */
  global?: boolean;
}

export interface LoadContextResult {
  settingsFile: string;
  installed: boolean;
  alreadyInstalled: boolean;
  agentsMdFound: boolean;
  dryRun: boolean;
  report: string;
}

export async function runLoadContext(options: LoadContextOptions): Promise<LoadContextResult> {
  const { projectPath, dryRun = false, antiCompaction = false, lazy = false, global: isGlobal = false } = options;

  const clauDir = isGlobal ? globalClaudeDir() : path.join(projectPath, ".claude");
  const settingsFile = path.join(clauDir, "settings.json");
  const agentsMdPath = path.join(projectPath, "AGENTS.md");
  const agentsMdFound = await fileExists(agentsMdPath);

  // Detect whether CLAUDE.md already imports @AGENTS.md (agents-sync init default).
  // If it does, the SessionStart hook and the @-import both load AGENTS.md — the hook
  // is still useful for subdirectory sessions where CLAUDE.md isn't auto-loaded, but
  // users should know context will appear once (Claude Code deduplicates system-reminders).
  const claudeMdPath = path.join(projectPath, "CLAUDE.md");
  let claudeMdHasImport = false;
  if (await fileExists(claudeMdPath)) {
    try {
      const claudeMd = await (await import("node:fs/promises")).readFile(claudeMdPath, "utf8");
      claudeMdHasImport = claudeMd.includes("@AGENTS.md");
    } catch { /* ignore */ }
  }

  const { alreadyInstalled, file } = await installSessionStartHook(projectPath, dryRun, clauDir);

  let antiCompactionInstalled = false;
  if (antiCompaction) {
    const result = await installPreToolUseHook(projectPath, dryRun, clauDir);
    antiCompactionInstalled = !result.alreadyInstalled;
  }

  let lazyInstalled = false;
  if (lazy) {
    const result = await installLazyHook(projectPath, dryRun, clauDir);
    lazyInstalled = !result.alreadyInstalled;
  }

  const lines: string[] = [];

  if (isGlobal && !agentsMdFound) {
    lines.push("⚠  No AGENTS.md found in this directory (global hook will still work in any project that has one).");
    lines.push("");
  } else if (!isGlobal && !agentsMdFound) {
    lines.push("⚠  No AGENTS.md found in this directory.");
    lines.push("   The hook will still be installed — it silently no-ops when AGENTS.md is absent.");
    lines.push("   Create AGENTS.md manually, or run `agents-sync init .` to generate one.");
    lines.push("");
  }

  if (alreadyInstalled) {
    lines.push(`✓ SessionStart hook already installed — nothing to do.`);
    lines.push(`  → ${file}`);
  } else if (dryRun) {
    lines.push("DRY RUN — would write:");
    lines.push(`  → ${file}`);
  } else {
    lines.push("✓ Installed Claude Code SessionStart hook");
    lines.push(`  → ${file}`);
    if (antiCompactionInstalled) {
      lines.push("✓ Installed anti-compaction PreToolUse hook");
      lines.push("  → AGENTS.md re-injected on every tool call (survives context compaction).");
    }
    if (lazyInstalled) {
      lines.push("✓ Installed lazy-loading instruction");
      lines.push("  → Claude will check for AGENTS.md in subdirectories it enters (monorepo support).");
    }
    lines.push("");
    if (isGlobal) {
      lines.push("AGENTS.md will now be auto-loaded in every Claude Code session, across all projects.");
      lines.push("Works from any directory — walks up to git root to find all AGENTS.md files.");
      lines.push("");
      lines.push("To remove:  agents-sync unload-context --global");
    } else {
      lines.push("AGENTS.md will now be auto-loaded as context at the start of every Claude Code session.");
      lines.push("Works from subdirectories — walks up to git root to find all AGENTS.md files.");
      lines.push("");
      lines.push("To remove:  agents-sync unload-context .");
    }
    if (claudeMdHasImport && !isGlobal) {
      lines.push("");
      lines.push("ℹ  CLAUDE.md already imports @AGENTS.md — that covers the main session.");
      lines.push("   This hook adds coverage for subdirectory sessions where CLAUDE.md isn't auto-loaded.");
      lines.push("   Claude Code deduplicates content, so AGENTS.md won't appear twice in context.");
    }
  }

  return {
    settingsFile,
    installed: !alreadyInstalled,
    alreadyInstalled,
    agentsMdFound,
    dryRun,
    report: lines.join("\n"),
  };
}

export async function runUnloadContext(options: LoadContextOptions): Promise<{ report: string }> {
  const { projectPath, dryRun = false, global: isGlobal = false } = options;
  const clauDir = isGlobal ? globalClaudeDir() : undefined;
  const session = await removeSessionStartHook(projectPath, dryRun, clauDir);
  const preToolUse = await removePreToolUseHook(projectPath, dryRun, clauDir);
  const lazy = await removeLazyHook(projectPath, dryRun, clauDir);

  if (!session.found && !preToolUse.found && !lazy.found) {
    return { report: "No agents-sync context hooks found — nothing to remove." };
  }

  if (dryRun) {
    const targets = [
      session.found && session.file,
      preToolUse.found && preToolUse.file,
      lazy.found && lazy.file,
    ].filter(Boolean);
    return { report: `DRY RUN — would remove agents-sync hooks from:\n${targets.map((f) => `  → ${f}`).join("\n")}` };
  }

  const lines: string[] = [];
  if (session.found) lines.push(`✓ Removed SessionStart hook\n  → ${session.file}`);
  if (preToolUse.found) lines.push(`✓ Removed anti-compaction PreToolUse hook\n  → ${preToolUse.file}`);
  if (lazy.found) lines.push(`✓ Removed lazy-loading instruction\n  → ${lazy.file}`);
  return { report: lines.join("\n") };
}
