/**
 * agents-sync load-context
 *
 * Installs only the Claude Code SessionStart hook — no scanner, no API call,
 * no AGENTS.md generation.  Works on any project that already has an AGENTS.md,
 * whether it was written by hand, generated by this tool, or synced from another
 * AI tool.
 *
 * This is the minimal entry point for the reading side of the agents-sync
 * pipeline.  For the full pipeline (generate + derive + drift detection) use
 * `init` instead.
 */
import path from "node:path";
import { fileExists } from "../lib/file-utils.js";
import {
  installSessionStartHook,
  removeSessionStartHook,
  installPreToolUseHook,
  removePreToolUseHook,
  installLazyHook,
  removeLazyHook,
} from "./install-hook.js";

export interface LoadContextOptions {
  projectPath: string;
  dryRun?: boolean;
  /**
   * Also install a PreToolUse hook that re-injects AGENTS.md on every tool
   * call.  Protects against Claude Code dropping context after compaction.
   * Only needed if you are NOT using CLAUDE.md (which re-reads @AGENTS.md
   * automatically after compaction).
   * @default false
   */
  antiCompaction?: boolean;
  /**
   * Install a SessionStart instruction that tells Claude to check for AGENTS.md
   * in subdirectories it enters.  Useful in monorepos where each package has
   * its own AGENTS.md below the project root.
   * @default false
   */
  lazy?: boolean;
}

export interface LoadContextResult {
  settingsFile: string;
  installed: boolean;
  alreadyInstalled: boolean;
  agentsMdFound: boolean;
  dryRun: boolean;
  report: string;
}

export async function runLoadContext(options: LoadContextOptions): Promise<LoadContextResult> {
  const { projectPath, dryRun = false, antiCompaction = false, lazy = false } = options;

  const settingsFile = path.join(projectPath, ".claude", "settings.json");
  const agentsMdPath = path.join(projectPath, "AGENTS.md");
  const agentsMdFound = await fileExists(agentsMdPath);

  const { alreadyInstalled, file } = await installSessionStartHook(projectPath, dryRun);

  let antiCompactionInstalled = false;
  if (antiCompaction) {
    const result = await installPreToolUseHook(projectPath, dryRun);
    antiCompactionInstalled = !result.alreadyInstalled;
  }

  let lazyInstalled = false;
  if (lazy) {
    const result = await installLazyHook(projectPath, dryRun);
    lazyInstalled = !result.alreadyInstalled;
  }

  const lines: string[] = [];

  if (!agentsMdFound) {
    lines.push("⚠  No AGENTS.md found in this directory.");
    lines.push("   The hook will still be installed — it silently no-ops when AGENTS.md is absent.");
    lines.push("   Create AGENTS.md manually, or run `agents-sync init .` to generate one.");
    lines.push("");
  }

  if (alreadyInstalled) {
    lines.push("✓ SessionStart hook already installed — nothing to do.");
    lines.push(`  → ${file}`);
  } else if (dryRun) {
    lines.push("DRY RUN — would write:");
    lines.push(`  → ${file}`);
  } else {
    lines.push("✓ Installed Claude Code SessionStart hook");
    lines.push(`  → ${file}`);
    if (antiCompactionInstalled) {
      lines.push("✓ Installed anti-compaction PreToolUse hook");
      lines.push("  → AGENTS.md re-injected on every tool call (survives context compaction).");
    }
    if (lazyInstalled) {
      lines.push("✓ Installed lazy-loading instruction");
      lines.push("  → Claude will check for AGENTS.md in subdirectories it enters (monorepo support).");
    }
    lines.push("");
    lines.push("AGENTS.md will now be auto-loaded as context at the start of every Claude Code session.");
    lines.push("Works from subdirectories — walks up to git root to find all AGENTS.md files.");
    lines.push("");
    lines.push("To remove:  agents-sync unload-context .");
  }

  return {
    settingsFile,
    installed: !alreadyInstalled,
    alreadyInstalled,
    agentsMdFound,
    dryRun,
    report: lines.join("\n"),
  };
}

export async function runUnloadContext(options: LoadContextOptions): Promise<{ report: string }> {
  const { projectPath, dryRun = false } = options;
  const session = await removeSessionStartHook(projectPath, dryRun);
  const preToolUse = await removePreToolUseHook(projectPath, dryRun);
  const lazy = await removeLazyHook(projectPath, dryRun);

  if (!session.found && !preToolUse.found && !lazy.found) {
    return { report: "No agents-sync context hooks found — nothing to remove." };
  }

  if (dryRun) {
    const targets = [
      session.found && session.file,
      preToolUse.found && preToolUse.file,
      lazy.found && lazy.file,
    ].filter(Boolean);
    return { report: `DRY RUN — would remove agents-sync hooks from:\n${targets.map((f) => `  → ${f}`).join("\n")}` };
  }

  const lines: string[] = [];
  if (session.found) lines.push(`✓ Removed SessionStart hook\n  → ${session.file}`);
  if (preToolUse.found) lines.push(`✓ Removed anti-compaction PreToolUse hook\n  → ${preToolUse.file}`);
  if (lazy.found) lines.push(`✓ Removed lazy-loading instruction\n  → ${lazy.file}`);
  return { report: lines.join("\n") };
}
